

        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="index.html">Home</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="#">Dashboard</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="#">Admin Panel</a>
                </li>
            </ul>
            <div class="page-toolbar">
                <!--        <div class="btn-group pull-right">
                            <button type="button" class="btn btn-fit-height grey-salt dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true">
                                Actions <i class="fa fa-angle-down"></i>
                            </button>
                            <ul class="dropdown-menu pull-right" role="menu">
                                <li>
                                    <a href="#">Action</a>
                                </li>
                                <li>
                                    <a href="#">Another action</a>
                                </li>
                                <li>
                                    <a href="#">Something else here</a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="#">Separated link</a>
                                </li>
                            </ul>
                        </div>-->
            </div>
        </div>
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->
        <div class="tiles" >
            <div class="tile double bg-red-intense">
                <div class="tile-body">
                    <img src="../../assets/admin/pages/media/profile/photo1.png" alt="">
                    <h4>Shed One</h4>
                    <p>
                        Temperature : 60 <br> Humidity : 10
                    </p>
                </div>
                <div class="tile-object">
                    <div class="name">

                    </div>
                    <div class="number">
                        Status: Warning Temperature
                    </div>
                </div>
            </div>
            <div class="tile double bg-green-meadow">
                <div class="tile-body">
                    <img src="../../assets/admin/pages/media/profile/photo1.png" alt="">
                    <h4>Shed two</h4>
                    <p>
                        Temprature : 30 <br> Humidity : 10
                    </p>
                </div>
                <div class="tile-object">
                    <div class="name">

                    </div>
                    <div class="number">
                        Status: Controlled Condition
                    </div>
                </div>
            </div>
        </div>
