<!--<link rel="stylesheet" type="text/css" href="css/jquery.dataTables.css">-->
<div id="empty-datatables">
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="index.html">Home</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="#">Dashboard</a>
                    <i class="fa fa-angle-right"></i>
                </li>
                <li>
                    <a href="#">Data Tables</a>
                </li>
            </ul>
            <div class="page-toolbar">
                <!--        <div class="btn-group pull-right">
                            <button type="button" class="btn btn-fit-height grey-salt dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true">
                                Actions <i class="fa fa-angle-down"></i>
                            </button>
                            <ul class="dropdown-menu pull-right" role="menu">
                                <li>
                                    <a href="#">Action</a>
                                </li>
                                <li>
                                    <a href="#">Another action</a>
                                </li>
                                <li>
                                    <a href="#">Something else here</a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="#">Separated link</a>
                                </li>
                            </ul>
                        </div>-->
            </div>
        </div>
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->
        <div class="row">
            <div class="col-md-12">
                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet box grey-cascade">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-globe"></i>Current Readings
                        </div>
                        <div class="tools">
                            <a href="javascript:;" class="collapse">
                            </a>
                            <a class="set-H config"></i>
                            </a>
                            <a href="javascript:;" class="reload">
                            </a>
                            <a href="javascript:;" class="remove">
                            </a>
                        </div>
                    </div>
                    <div class="portlet-body">

                        <div class="table-toolbar">
                            <div class="row">

                                <div class="col-md-2">
                                    <div class="btn-group">
                                        <input type="text" id="date_from" required="" name="date_from"
                                               class="form-control has-error form-inline date-picker"
                                               placeholder="YYYY-MM-DD">

                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="btn-group">
                                        <input type="text" id="date_to" required="" name="date_to"
                                               class="form-control form-inline date-picker" placeholder="YYYY-MM-DD">
                                    </div>
                                </div>
                                <div class="col-md-2 hideOnPlot">
                                    <button type="button" id="btn_search" onclick="$('#tableData').empty();offset=0;searchTable()" class="btn green btn-block">
                                        <i class="fa fa-search"></i> Search
                                    </button>
                                </div>
                                <div class="col-md-2  hideOnPlot">
                                    <button type="button" id="btn_excel" class="btn blue-ebonyclay btn-block">
                                        <i class="glyphicon glyphicon-export"></i> Export to Excel
                                    </button>
                                </div>
                                <div class="col-md-2 hideOnPlot">
                                    <button type="button" id="btn_plot" onclick="plot();"
                                            class="btn blue-steel btn-block">
                                        <i class="fa fa-bar-chart"></i> Plot
                                    </button>
                                </div>
                                <div class="col-md-2 showOnPlot" hidden="" id="btn_dataTable">
                                    <button type="button" onclick="plot('Temprature');"
                                            class="btn blue-steel btn-block">
                                        <i class="glyphicon glyphicon-tasks"></i> Data Tables
                                    </button>
                                </div>
                                <div class="col-md-2 showOnPlot" hidden="">
                                    <button type="button" onclick="plotSelf();"
                                            class="btn blue-steel btn-block">
                                        <i class="icon icon-drop"></i> Plot
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="alert alert-danger" id="dateAlert" hidden="" role="alert" style="display:hide;">
                            Please Select Dates
                        </div>
                        <div class="table-responsive  hideOnPlot" >
                            <table class="table table-striped table-bordered table-hover control-h" id="table2excel" >
                                <thead>
                                <tr>
                                    <th>
                                        Shed Name
                                    </th>
                                    <th>
                                        Date Time
                                    </th>
                                    <th class="numeric">
                                        Temperature
                                    </th>
                                    <th class="numeric">
                                        Humidity
                                    </th>
                                </tr>
                                </thead>
                                <tbody id="tableData">

                                </tbody>
                            </table>

                            <p id="norecord"></p>
                        </div>
                        <div id="chartdiv" class="chart" style="height: 400px; width: 900px">
                        </div>
                    </div>
                </div>
                <!-- END EXAMPLE TABLE PORTLET-->
            </div>
        </div>
<!--    <script type="text/javascript" src="js/jquery.dataTables.min.js"></script>-->
        <script type="text/javascript" src="js/extable.js"></script>
<script type="text/javascript" src="js/tables.js"></script>


</div>