<!-- BEGIN CONTENT -->

<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title">Farm Monitoring Dashboard
            <small>Admin Area</small>
            <select class="select2-highlighted pull-right" onchange="searchTable();" id="select_device" name="select_device">
                <option>Loading ...</option>
            </select>
        </h3>
        <div data-bind="page: {id: 'page-dashboard',fx: 'slide', sourceOnShow: 'pe/dashboard',role : 'start'}">
        </div>
        <div data-bind="page: {id: 'page-livetemp',fx: 'slide', sourceOnShow: 'pe/livetemp'}">
        </div>
        <div data-bind="page: {id: 'page-livehumid',fx: 'slide', sourceOnShow: 'pe/livehumid'}">
        </div>
        <div
            data-bind="page: {id: 'page-datatables',fx: 'slide',beforeShow:ComponentsPickers.init() ,afterShow:searchTable, sourceOnShow: 'pe/datatables'}">
        </div>
    </div>
    <!-- END PAGE CONTENT-->
</div>
<!-- END CONTENT -->
