<!-- BEGIN CONTENT -->

<div class="page-content-wrapper">
    <div class="page-content">
        <h3 class="page-title">Farm Monitoring Dashboard
            <small>Admin Area&nbsp;<span class="label label-danger">
								Temperature Limit : <b id="tht">20</b> </span>&nbsp;<span class="label label-success">
								Humidity Limit : <b id="thh">20</b>  </span></small>

            <select class="select2-highlighted pull-right" onchange="searchTable();" id="select_device" name="select_device">
                <option>Loading ...</option>
            </select>
        </h3>

<!--        <script>-->
<!--            var barlength=0;-->
<!--            var timer =  setInterval(function(){-->
<!--                console.log("s");-->
<!--                if(barlength !=100)-->
<!--                barlength +=2;-->
<!--                $('.progress-bar').css('width', barlength+'%').attr('aria-valuenow', barlength);-->
<!--                if(barlength>=100){-->
<!--                    $( ".progress" ).remove();-->
<!--                    clearInterval(timer);-->
<!--                }-->
<!--            },100)</script>-->
<!--        <div class="progress progress-striped active">-->
<!--            <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 40%">-->
<!--            </div>-->
<!--        </div>-->
        <div data-bind="page: {id: 'page-dashboard',fx: 'fade',beforeHide:function(){$('#empty-dashboard').empty()}, sourceOnShow: 'pe/dashboard',role : 'start'}">
        </div>
        <div data-bind="page: {id: 'page-liveview',fx: 'fade',beforeHide:function(){$('#empty-liveview').empty()}, sourceOnShow: 'pe/liveview'}">
        </div>
        <div
            data-bind="page: {id: 'page-datatables',fx: 'fade',beforeShow:ComponentsPickers.init() ,beforeHide:function(){$('#empty-datatables').empty()},afterShow:searchTable, sourceOnShow: 'pe/datatables'}">
        </div>
    </div>
    <!-- END PAGE CONTENT-->
</div>
<!-- END CONTENT -->