<div data-bind="page: {id: 'page-dashboard',fx: 'slide', sourceOnShow: 'pe/dashboard .page-content-wrapper',role : 'start'}">
</div>
<div data-bind="page: {id: 'page-livetemp',fx: 'slide', sourceOnShow: 'pe/livetemp .page-content-wrapper'}">
</div>
<div data-bind="page: {id: 'page-livehumid',fx: 'slide', sourceOnShow: 'pe/livehumid .page-content-wrapper'}">
</div>
<div data-bind="page: {id: 'page-datatables',fx: 'slide',beforeShow:ComponentsPickers.init() ,afterShow:searchTable, sourceOnShow: 'pe/datatables .page-content-wrapper'}">
</div>