<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Pe\Module'                        => __DIR__ . '/Module.php',
    'Pe\Controller\PeController' => __DIR__ . '/src/Pe/Controller/PeController.php',
    'PeTest\Framework\TestCase'        => __DIR__ . '/tests/Pe/Framework/TestCase.php',
    'PeTest\SampleTest'                => __DIR__ . '/tests/Pe/SampleTest.php',
);
